#include "stm32f1xx.h"
#include "gpio_user.h"
#include "gpio.h"

void GPIO_Init (void){

	//Port clock setting 
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPFEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPDEN; 

	//User LED gpio pin config
	GPIO_SetPinMode (PORT_LED_ACTIVE, PIN_LED_ACTIVE, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_LED_ACTIVE, PIN_LED_ACTIVE, GPIO_MODE_OUTPUT_10MHz);
		
	GPIO_SetPinMode (PORT_LED_FAILTURE, PIN_LED_FAILTURE, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_LED_FAILTURE, PIN_LED_FAILTURE, GPIO_MODE_OUTPUT_10MHz);
	
	//TRIAC gpio pin  config
	GPIO_SetPinMode (PORT_TRIAC_1, PIN_TRIAC_1, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_1, PIN_TRIAC_1, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_2, PIN_TRIAC_2, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_2, PIN_TRIAC_2, GPIO_MODE_OUTPUT_10MHz);

	GPIO_SetPinMode (PORT_TRIAC_3, PIN_TRIAC_3, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_3, PIN_TRIAC_3, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_4, PIN_TRIAC_4, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_4, PIN_TRIAC_4, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_5, PIN_TRIAC_5, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_5, PIN_TRIAC_5, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_6, PIN_TRIAC_6, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_6, PIN_TRIAC_6, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_7, PIN_TRIAC_7, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_7, PIN_TRIAC_7, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_8, PIN_TRIAC_8, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_8, PIN_TRIAC_8, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (PORT_TRIAC_9, PIN_TRIAC_9, GPIO_MODE_OUTPUT);
	GPIO_SetPinSpeed(PORT_TRIAC_9, PIN_TRIAC_9, GPIO_MODE_OUTPUT_10MHz);
	
	//MOSFET gpio pin config

}
