#include "gpio_us.h"

void GPIO_Init (void)
{
	//Port clock setting 
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN; //Enabling the clock PORT B
	RCC->APB2ENR |= RCC_APB2ENR_IOPFEN; //Enabling the clock PORT F
	RCC->APB2ENR |= RCC_APB2ENR_IOPGEN; //Enabling the clock PORT G
	RCC->APB2ENR |= RCC_APB2ENR_IOPEEN; //Enabling the clock PORT E
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN; //Enabling the clock PORT C
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN; //Clock alternate port mode  enable

	GPIO_SetPinMode (PORT_LED_ACTIVE, PIN_LED_ACTIVE, GPIO_MODE_OUTPUT);									//Led GREEN
	GPIO_SetPinSpeed(PORT_LED_ACTIVE, PIN_LED_ACTIVE, GPIO_MODE_OUTPUT_10MHz);

	GPIO_SetPinMode (PORT_LED_FAILTURE, PIN_LED_FAILTURE, GPIO_MODE_OUTPUT);								//Led RED
	GPIO_SetPinSpeed(PORT_LED_FAILTURE, PIN_LED_FAILTURE, GPIO_MODE_OUTPUT_10MHz);
	
	GPIO_SetPinMode (GPIOG, GPIO_PIN_4, GPIO_MODE_OUTPUT);													//Inhibit money
	GPIO_SetPinSpeed(GPIOG, GPIO_PIN_4, GPIO_MODE_OUTPUT_10MHz);

	//GPIO_SetPinMode (GPIOG, GPIO_PIN_5, GPIO_MODE_INPUT);													//DATA money
	//GPIO_SetPinPull(GPIOG, GPIO_PIN_5, GPIO_PULL_UP);

	GPIO_SetPinMode (GPIOG, GPIO_PIN_6, GPIO_MODE_OUTPUT);													//Inhibit coin
	GPIO_SetPinSpeed(GPIOG, GPIO_PIN_6, GPIO_MODE_OUTPUT_10MHz);
	
	//GPIO_SetPinMode (GPIOG, GPIO_PIN_7, GPIO_MODE_INPUT);													//DATA coin
	//GPIO_SetPinPull(GPIOG, GPIO_PIN_7, GPIO_PULL_UP);

	GPIO_SetPinMode(PORT_INPUT_PRESS_SENSOR, PIN_INPUT_PRESS_SENSOR, GPIO_MODE_INPUT);						//In pressure 
	GPIO_SetPinPull(PORT_INPUT_PRESS_SENSOR, PIN_INPUT_PRESS_SENSOR, GPIO_PULL_UP);
	
	GPIO_SetPinMode(PORT_OUTPUT_PRESS_SENSOR, PIN_OUTPUT_PRESS_SENSOR, GPIO_MODE_INPUT);					//Out pressure
	GPIO_SetPinPull(PORT_OUTPUT_PRESS_SENSOR, PIN_OUTPUT_PRESS_SENSOR, GPIO_PULL_UP);
	
	GPIO_SetPinMode(PORT_BUTTON_DOWN, PIN_BUTTON_DOWN, GPIO_MODE_INPUT);									//Button 1
	GPIO_SetPinPull(PORT_BUTTON_DOWN, PIN_BUTTON_DOWN, GPIO_PULL_UP);
	
	GPIO_SetPinMode(PORT_BUTTON_UP, 	PIN_BUTTON_UP, GPIO_MODE_INPUT);									//Button 2
	GPIO_SetPinPull(PORT_BUTTON_UP, 	PIN_BUTTON_UP, GPIO_PULL_UP);
	
	GPIO_SetPinMode(PORT_BUTTON_LEFT, PIN_BUTTON_LEFT, GPIO_MODE_INPUT);									//Button 3
	GPIO_SetPinPull(PORT_BUTTON_LEFT, PIN_BUTTON_LEFT, GPIO_PULL_UP);
	
	GPIO_SetPinMode(PORT_BUTTON_RIGHT, PIN_BUTTON_RIGHT, GPIO_MODE_INPUT);									//Button 4
	GPIO_SetPinPull(PORT_BUTTON_RIGHT, PIN_BUTTON_RIGHT, GPIO_PULL_NO);
	
	GPIO_SetPinMode(PORT_BUTTON_FAIL, PIN_BUTTON_FAIL, GPIO_MODE_INPUT);									//Ext button fail
	GPIO_SetPinPull(PORT_BUTTON_FAIL, PIN_BUTTON_FAIL, GPIO_PULL_UP);
	
}

uint8_t Is_InPressSensor(void)
{
	return (PORT_INPUT_PRESS_SENSOR->IDR & DATA_INPUT_PRESS_SENSOR) != 0;
}

uint8_t Is_OutPressSensor(void)
{
	return (PORT_OUTPUT_PRESS_SENSOR->IDR & DATA_OUTPUT_PRESS_SENSOR) != 0;
}

uint8_t Is_ExtButFailDown(void)
{
	return (PORT_BUTTON_FAIL->IDR & DATA_BUTTON_FAIL) != 0;
}

uint8_t Is_ButtonLeft(void)
{
	return (PORT_BUTTON_LEFT->IDR & DATA_BUTTON_LEFT) == 0;
}

uint8_t Is_ButtonRight(void)
{
	return (PORT_BUTTON_RIGHT->IDR & DATA_BUTTON_RIGHT) == 0;
}

uint8_t Is_ButtonUp(void)
{
	return (PORT_BUTTON_UP->IDR & DATA_BUTTON_UP) == 0;
}

uint8_t Is_ButtonDown(void)
{
	return (PORT_BUTTON_DOWN->IDR & DATA_BUTTON_DOWN) == 0;
}
